model:
  name: dmis-lab/biobert-base-cased-v1.1
  evaluation:
    remove_bilu: true

hyper_params:
  tokens_per_batch: 32
  batch_size: 32
  epochs: 4
  learning_rate: 2e-5
  shuffle: True

datasets:
  train: ./data/input/train.csv
  test: ./data/input/test.csv
  features: ./data/input/features.csv
  patient_notes: ./data/input/patient_notes.csv

caching:
  tensorboard_profiler: gpu/
  tensorboard_metrics: metrics/
  finetuned_ner_model: model/
  finetuned_ner_metrics: model/evaluation_metrics.json
